version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Adjust port if needed
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    environment:
      POSTGRES_DB: Recipes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: 123

      #echo "123" | docker secret create postgres_password -
      #POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

secrets:
  postgres_password:
    external: true

volumes:
  db-data: